// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwyjlpeydehzbzmctabl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eWpscGV5ZGVoemJ6bWN0YWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTI1NzAsImV4cCI6MjA2NDUyODU3MH0.vvkhrQ7muketRKAnFD3stOhmBHZUlE3a2qevxrYUb48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);